apiVersion: v1
kind: ServiceAccount
metadata:
  name: skill-radar
  namespace: skill-radar-dev
  annotations:
    iam.gke.io/gcp-service-account: skill-radar-runtime@sinapse-core.iam.gserviceaccount.com
