apiVersion: v1
kind: ServiceAccount
metadata:
  name: skill-radar-dev
  namespace: public-webapp-dev
  annotations:
    iam.gke.io/gcp-service-account: skill-radar-runtime@premier-socle-sinapse.iam.gserviceaccount.com
