import fs from 'fs';
import path from 'path';
import { AsyncLocalStorage } from 'async_hooks';
import { execFileSync } from 'child_process';
import pg from 'pg';
import { seedCatalog } from './seed-catalog.js';
import { safeJsonParse } from './types.js';
const { Pool, types: pgTypes } = pg;
const INIT_SQL_PATH = path.join(process.cwd(), 'server', 'db', 'postgres-init.sql');
const CATALOG_VERSION = '5.1.0';
export const TEST_DATABASE_HANDLE = 'postgres';
// Preserve the app's current JSON.parse/stringify and date-string behavior
// while the storage type moves to JSONB/TIMESTAMPTZ.
pgTypes.setTypeParser(20, (value) => Number(value));
pgTypes.setTypeParser(114, (value) => value);
pgTypes.setTypeParser(3802, (value) => value);
pgTypes.setTypeParser(1082, (value) => value);
pgTypes.setTypeParser(1114, (value) => value);
pgTypes.setTypeParser(1184, (value) => value);
export interface MemberEvaluation {
    ratings: Record<string, number>;
    experience: Record<string, number>;
    skippedCategories: string[];
    declinedCategories: string[];
    submittedAt: string | null;
    profileSummary: string | null;
}
export interface DbRunResult {
    changes: number;
    lastInsertRowid?: number | string;
}
type Queryable = pg.Pool | pg.PoolClient;
const txClientStore = new AsyncLocalStorage<pg.PoolClient>();
let pool: pg.Pool | null = null;
let db: AsyncDb | null = null;
function requirePool(): pg.Pool {
    if (!pool)
        throw new Error('Database not initialized. Call initDatabase() first.');
    return pool;
}
function currentQueryable(): Queryable {
    return txClientStore.getStore() ?? requirePool();
}
function normalizeParams(params: unknown[]): unknown[] {
    return params;
}
function convertPlaceholders(sql: string): string {
    let idx = 0;
    let out = '';
    let inSingle = false;
    let inDouble = false;
    let inLineComment = false;
    let inBlockComment = false;
    let dollarQuoteTag: string | null = null;
    for (let i = 0; i < sql.length; i++) {
        const ch = sql[i];
        const next = sql[i + 1];
        if (dollarQuoteTag !== null) {
            const closing = `$${dollarQuoteTag}$`;
            if (sql.startsWith(closing, i)) {
                out += closing;
                i += closing.length - 1;
                dollarQuoteTag = null;
            }
            else {
                out += ch;
            }
            continue;
        }
        if (inLineComment) {
            out += ch;
            if (ch === '\n')
                inLineComment = false;
            continue;
        }
        if (inBlockComment) {
            out += ch;
            if (ch === '*' && next === '/') {
                out += next;
                i++;
                inBlockComment = false;
            }
            continue;
        }
        if (!inSingle && !inDouble && ch === '-' && next === '-') {
            out += ch + next;
            i++;
            inLineComment = true;
            continue;
        }
        if (!inSingle && !inDouble && ch === '/' && next === '*') {
            out += ch + next;
            i++;
            inBlockComment = true;
            continue;
        }
        if (!inSingle && !inDouble && ch === '$') {
            const match = sql.slice(i).match(/^\$([A-Za-z_][A-Za-z0-9_]*)?\$/);
            if (match) {
                const opener = match[0];
                dollarQuoteTag = match[1] ?? '';
                out += opener;
                i += opener.length - 1;
                continue;
            }
        }
        if (!inDouble && ch === "'") {
            out += ch;
            if (inSingle && next === "'") {
                out += next;
                i++;
            }
            else {
                inSingle = !inSingle;
            }
            continue;
        }
        if (!inSingle && ch === '"') {
            out += ch;
            inDouble = !inDouble;
            continue;
        }
        if (!inSingle && !inDouble && ch === '?') {
            idx++;
            out += `$${idx}`;
            continue;
        }
        out += ch;
    }
    return out;
}
function translateSqlDialect(sql: string): string {
    let out = sql.trim().replace(/;+\s*$/g, '');
    out = out
        .replace(/\bPRAGMA\b[^\n;]*(;)?/gi, '')
        .replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        .replace(/\bAUTOINCREMENT\b/gi, '')
        .replace(/\bCREATE\s+TABLE\s+(IF\s+NOT\s+EXISTS\s+)?user\b/gi, 'CREATE TABLE $1"user"')
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'-(\d+)\s+minutes?'\s*\)/gi, "($1::timestamptz - interval '$2 minutes')")
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'-(\d+)\s+hours?'\s*\)/gi, "($1::timestamptz - interval '$2 hours')")
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'-(\d+)\s+days?'\s*\)/gi, "($1::timestamptz - interval '$2 days')")
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'\+(\d+)\s+minutes?'\s*\)/gi, "($1::timestamptz + interval '$2 minutes')")
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'\+(\d+)\s+hours?'\s*\)/gi, "($1::timestamptz + interval '$2 hours')")
        .replace(/\bdatetime\(\s*([^,()]+)\s*,\s*'\+(\d+)\s+days?'\s*\)/gi, "($1::timestamptz + interval '$2 days')")
        .replace(/\bdatetime\('now'\s*,\s*'-'\s*\|\|\s*(\?)\s*\|\|\s*'\s+minutes?'\s*\)/gi, "now() - (($1)::text || ' minutes')::interval")
        .replace(/\bdatetime\('now'\s*,\s*'-'\s*\|\|\s*(\?)\s*\|\|\s*'\s+days?'\s*\)/gi, "now() - (($1)::text || ' days')::interval")
        .replace(/\bdatetime\('now'\s*,\s*'\+(\d+)\s+days?'\)/gi, "now() + interval '$1 days'")
        .replace(/\bdatetime\('now'\s*,\s*'-(\d+)\s+days?'\)/gi, "now() - interval '$1 days'")
        .replace(/\bdatetime\('now'\s*,\s*'\+(\d+)\s+hours?'\)/gi, "now() + interval '$1 hours'")
        .replace(/\bdatetime\('now'\s*,\s*'-(\d+)\s+hours?'\)/gi, "now() - interval '$1 hours'")
        .replace(/\bdatetime\('now'\s*,\s*'\+(\d+)\s+minutes?'\)/gi, "now() + interval '$1 minutes'")
        .replace(/\bdatetime\('now'\s*,\s*'-(\d+)\s+minutes?'\)/gi, "now() - interval '$1 minutes'")
        .replace(/\bdatetime\('now'\)/gi, 'now()')
        .replace(/\bdatetime\(([^)]+)\)/gi, '$1::timestamptz')
        .replace(/\bCURRENT_TIMESTAMP\b/g, 'now()')
        .replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO')
        .replace(/\bUPDATE\s+OR\s+IGNORE\b/gi, 'UPDATE')
        .replace(/\bINSERT\s+OR\s+REPLACE\s+INTO\b/gi, 'INSERT INTO')
        .replace(/\b([a-zA-Z_][\w.]*)\s*->>\s*'([a-zA-Z0-9_]+)'/g, "($1::jsonb)->>'$2'")
        .replace(/\bjson_extract\(\s*([a-zA-Z_][\w.]*)\s*,\s*'\$\.([a-zA-Z0-9_]+)'\s*\)/gi, "($1->>'$2')")
        .replace(/\bUPDATE\s+user\b/gi, 'UPDATE "user"')
        .replace(/\bFROM\s+user\b/gi, 'FROM "user"')
        .replace(/\bJOIN\s+user\b/gi, 'JOIN "user"')
        .replace(/\bINTO\s+user\b/gi, 'INTO "user"')
        .replace(/\bDELETE\s+FROM\s+user\b/gi, 'DELETE FROM "user"')
        .replace(/\bAS\s+([a-z][A-Za-z0-9_]*[A-Z][A-Za-z0-9_]*)\b/g, 'AS "$1"')
        .replace(/\bemailVerified\b/g, '"emailVerified"')
        .replace(/\buserId\b/g, '"userId"');
    const isInsert = /^\s*INSERT\s+INTO\b/i.test(out);
    const cameFromIgnore = /\bINSERT\s+OR\s+IGNORE\s+INTO\b/i.test(sql);
    if (isInsert && cameFromIgnore && !/\bON\s+CONFLICT\b/i.test(out)) {
        out += ' ON CONFLICT DO NOTHING';
    }
    return out;
}
function translateSql(sql: string): string {
    return convertPlaceholders(translateSqlDialect(sql));
}
function isSyncTestMode(): boolean {
    return process.env.POSTGRES_SYNC_TEST_MODE === 'true';
}
function sqlLiteral(value: unknown): string {
    if (value === null || value === undefined)
        return 'NULL';
    if (Array.isArray(value))
        return `ARRAY[${value.map(sqlLiteral).join(', ')}]`;
    if (Buffer.isBuffer(value))
        return `decode('${value.toString('hex')}', 'hex')`;
    if (value instanceof Date)
        return `'${value.toISOString().replace(/'/g, "''")}'`;
    if (typeof value === 'number') {
        if (!Number.isFinite(value))
            throw new Error(`Cannot bind non-finite number to SQL: ${value}`);
        return String(value);
    }
    if (typeof value === 'boolean')
        return value ? '1' : '0';
    if (typeof value === 'object')
        return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
    return `'${String(value).replace(/'/g, "''")}'`;
}
function injectLiteralParams(sql: string, params: unknown[]): string {
    let idx = 0;
    let out = '';
    let inSingle = false;
    let inDouble = false;
    let inLineComment = false;
    let inBlockComment = false;
    let dollarQuoteTag: string | null = null;
    for (let i = 0; i < sql.length; i++) {
        const ch = sql[i];
        const next = sql[i + 1];
        if (dollarQuoteTag !== null) {
            const closing = `$${dollarQuoteTag}$`;
            if (sql.startsWith(closing, i)) {
                out += closing;
                i += closing.length - 1;
                dollarQuoteTag = null;
            }
            else {
                out += ch;
            }
            continue;
        }
        if (inLineComment) {
            out += ch;
            if (ch === '\n')
                inLineComment = false;
            continue;
        }
        if (inBlockComment) {
            out += ch;
            if (ch === '*' && next === '/') {
                out += next;
                i++;
                inBlockComment = false;
            }
            continue;
        }
        if (!inSingle && !inDouble && ch === '-' && next === '-') {
            out += ch + next;
            i++;
            inLineComment = true;
            continue;
        }
        if (!inSingle && !inDouble && ch === '/' && next === '*') {
            out += ch + next;
            i++;
            inBlockComment = true;
            continue;
        }
        if (!inSingle && !inDouble && ch === '$') {
            const match = sql.slice(i).match(/^\$([A-Za-z_][A-Za-z0-9_]*)?\$/);
            if (match) {
                const opener = match[0];
                dollarQuoteTag = match[1] ?? '';
                out += opener;
                i += opener.length - 1;
                continue;
            }
        }
        if (!inDouble && ch === "'") {
            out += ch;
            if (inSingle && next === "'") {
                out += next;
                i++;
            }
            else {
                inSingle = !inSingle;
            }
            continue;
        }
        if (!inSingle && ch === '"') {
            out += ch;
            inDouble = !inDouble;
            continue;
        }
        if (!inSingle && !inDouble && ch === '?') {
            if (idx >= params.length)
                throw new Error(`SQL expected more bind params: ${sql}`);
            out += sqlLiteral(params[idx++]);
            continue;
        }
        out += ch;
    }
    if (idx !== params.length)
        throw new Error(`SQL received ${params.length} bind params but used ${idx}: ${sql}`);
    return convertPlaceholders(out);
}
function syncPsql(sql: string): string {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString)
        throw new Error('DATABASE_URL is required for Postgres test queries.');
    try {
        return execFileSync('psql', ['-X', '--no-psqlrc', '-qAt', '--set=ON_ERROR_STOP=1', connectionString, '-c', sql], {
            encoding: 'utf-8',
            maxBuffer: 50 * 1024 * 1024,
            stdio: ['ignore', 'pipe', 'pipe'],
        }).trim();
    }
    catch (err) {
        const detail = err && typeof err === 'object' && 'stderr' in err ? String((err as { stderr?: unknown }).stderr) : String(err);
        throw new Error(`[postgres-test] query failed: ${detail}\nSQL:\n${sql}`);
    }
}
const jsonLikeColumns = new Set([
    'ai_profile',
    'ai_suggestions',
    'answers',
    'data_json',
    'email_snapshot',
    'evidence',
    'experience',
    'payload',
    'poste_snapshot',
    'ratings',
    'reasoning',
    'role_aware_suggestions',
    'skipped_categories',
    'declined_categories',
]);
function normalizeJsonLikeRows<T>(rows: T[]): T[] {
    for (const row of rows as Array<Record<string, unknown>>) {
        for (const key of Object.keys(row)) {
            const value = row[key];
            if (jsonLikeColumns.has(key) && value !== null && typeof value === 'object') {
                row[key] = JSON.stringify(value);
            }
        }
    }
    return rows;
}
function withLiteralParams(sql: string, params: unknown[]): string {
    const dialect = translateSqlDialect(sql)
        .replace(/\b([a-zA-Z_][\w.]*)\s*->>\s*'([a-zA-Z0-9_]+)'/g, "($1::jsonb)->>'$2'");
    if (/\$\d+\b/.test(dialect)) {
        const used = new Set<number>();
        const replaced = dialect.replace(/\$(\d+)\b/g, (_match, rawIndex: string) => {
            const index = Number(rawIndex);
            used.add(index);
            if (index < 1 || index > params.length)
                throw new Error(`SQL bind index $${index} has no parameter: ${sql}`);
            return sqlLiteral(params[index - 1]);
        });
        if (used.size !== params.length)
            throw new Error(`SQL received ${params.length} bind params but used ${used.size}: ${sql}`);
        return replaced;
    }
    return injectLiteralParams(dialect, params);
}
function syncAll<T>(sql: string, params: unknown[] = []): T[] {
    const translated = withLiteralParams(sql, params);
    const json = syncPsql(`WITH __q AS (${translated}) SELECT COALESCE(json_agg(__q), '[]'::json)::text FROM __q`);
    return json ? normalizeJsonLikeRows(JSON.parse(json) as T[]) : [];
}
function statementWithReturning(sql: string): string {
    if (/\bRETURNING\b/i.test(sql))
        return sql;
    if (/^\s*(INSERT|UPDATE|DELETE)\b/i.test(sql))
        return `${sql} RETURNING *`;
    return sql;
}
function syncRun(sql: string, params: unknown[] = []): DbRunResult {
    const translated = statementWithReturning(withLiteralParams(sql, params));
    if (!/^\s*(WITH|INSERT|UPDATE|DELETE)\b/i.test(translated)) {
        syncPsql(translated);
        return { changes: 0 };
    }
    const json = syncPsql(`WITH __q AS (${translated}) SELECT json_build_object('rowCount', COUNT(*), 'rows', COALESCE(json_agg(__q), '[]'::json))::text FROM __q`);
    const parsed = json ? JSON.parse(json) as { rowCount: number; rows: Array<{ id?: number | string }> } : { rowCount: 0, rows: [] };
    return {
        changes: Number(parsed.rowCount ?? 0),
        lastInsertRowid: parsed.rows[0]?.id,
    };
}
function syncExec(sql: string): void {
    const translated = translateSqlDialect(sql)
        .replace(/\bCURRENT_TIMESTAMP\b/g, 'now()')
        .replace(/\bTRUE\b/g, '1')
        .replace(/\bFALSE\b/g, '0');
    if (translated.trim())
        syncPsql(convertPlaceholders(translated));
}
export const __syncDbForTests = {
    all: syncAll,
    run: syncRun,
    exec: syncExec,
};
async function query(sql: string, params: unknown[] = []) {
    const translated = translateSql(sql);
    return currentQueryable().query(translated, params);
}
export class AsyncStmt<TDefault = unknown> {
    private readonly sql: string;

    constructor(sql: string) {
        this.sql = sql;
    }
    all<T = TDefault>(...params: unknown[]): Promise<T[]> {
        if (isSyncTestMode())
            return syncAll<T>(this.sql, normalizeParams(params)) as unknown as Promise<T[]>;
        return query(this.sql, normalizeParams(params)).then((result) => result.rows as T[]);
    }
    get<T = TDefault>(...params: unknown[]): Promise<T | undefined> {
        if (isSyncTestMode())
            return syncAll<T>(this.sql, normalizeParams(params))[0] as unknown as Promise<T | undefined>;
        return query(this.sql, normalizeParams(params)).then((result) => result.rows[0] as T | undefined);
    }
    run(...params: unknown[]): Promise<DbRunResult> {
        if (isSyncTestMode())
            return syncRun(this.sql, normalizeParams(params)) as unknown as Promise<DbRunResult>;
        return query(this.sql, normalizeParams(params)).then((result) => {
            const first = result.rows[0] as {
                id?: number | string;
            } | undefined;
            return {
                changes: result.rowCount ?? 0,
                lastInsertRowid: first?.id,
            };
        });
    }
}
export class AsyncDb {
    prepare<T = unknown>(sql: string): AsyncStmt<T> {
        return new AsyncStmt<T>(sql);
    }
    exec(sql: string): Promise<void> {
        if (isSyncTestMode()) {
            syncExec(sql);
            return undefined as unknown as Promise<void>;
        }
        return query(sql).then(() => undefined);
    }
    transaction<TArgs extends unknown[], TReturn>(fn: (...args: TArgs) => TReturn | Promise<TReturn>): (...args: TArgs) => Promise<TReturn> {
        return async (...args: TArgs): Promise<TReturn> => {
            const client = await requirePool().connect();
            const startedAt = Date.now();
            try {
                await client.query('BEGIN');
                const result = await txClientStore.run(client, async () => fn(...args));
                await client.query('COMMIT');
                const elapsed = Date.now() - startedAt;
                if (elapsed > 100)
                    console.warn(`[db] transaction took ${elapsed}ms`);
                return result;
            }
            catch (err) {
                try {
                    await client.query('ROLLBACK');
                }
                catch { /* ignore rollback failure */ }
                throw err;
            }
            finally {
                client.release();
            }
        };
    }
    close(): Promise<void> {
        if (pool) {
            const ending = pool;
            pool = null;
            db = null;
            return ending.end();
        }
        return Promise.resolve();
    }
    get waitingCount(): number {
        return requirePool().waitingCount;
    }
}
export function getDb(): AsyncDb {
    if (!db)
        throw new Error('Database not initialized. Call initDatabase() first.');
    return db;
}
export function getPgPool(): pg.Pool {
    return requirePool();
}
async function connectWithRetry(maxAttempts = 8): Promise<void> {
    let lastErr: unknown;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
        try {
            await requirePool().query('SELECT 1');
            return;
        }
        catch (err) {
            lastErr = err;
            const delay = Math.min(250 * 2 ** (attempt - 1), 5000);
            console.warn(`[db] connection attempt ${attempt}/${maxAttempts} failed; retrying in ${delay}ms`);
            await new Promise((resolve) => setTimeout(resolve, delay));
        }
    }
    throw lastErr;
}
function createPool(connectionString: string): pg.Pool {
    const created = new Pool({
        connectionString,
        min: Number(process.env.PG_POOL_MIN ?? 5),
        max: Number(process.env.PG_POOL_MAX ?? 20),
        connectionTimeoutMillis: Number(process.env.PG_CONNECT_TIMEOUT_MS ?? 5000),
        idleTimeoutMillis: Number(process.env.PG_IDLE_TIMEOUT_MS ?? 30000),
        application_name: process.env.PGAPPNAME ?? 'skill-radar',
    });
    created.on('error', (err) => console.error('[db] idle pg client error', err));
    return created;
}
async function reloadCatalogCacheIfAvailable(): Promise<void> {
    const catalog = await import('./catalog.js');
    if ('loadCatalogCache' in catalog && typeof catalog.loadCatalogCache === 'function') {
        await catalog.loadCatalogCache();
    }
}
async function applySchemaAndSeedData(): Promise<void> {
    const initSql = fs.readFileSync(INIT_SQL_PATH, 'utf-8');
    await requirePool().query("SELECT pg_advisory_lock(hashtext('skill-radar-schema-init'))");
    try {
        await requirePool().query(initSql);
        await seedBaselineData();
        await reloadCatalogCacheIfAvailable();
    }
    finally {
        await requirePool().query("SELECT pg_advisory_unlock(hashtext('skill-radar-schema-init'))");
    }
}
export async function initDatabase(): Promise<void> {
    if (db)
        return;
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) {
        throw new Error('DATABASE_URL is required. Skill Radar starts only with Postgres.');
    }
    pool = createPool(connectionString);
    db = new AsyncDb();
    await connectWithRetry();
    await applySchemaAndSeedData();
    console.log('Database initialized at DATABASE_URL');
}
async function seedBaselineData(): Promise<void> {
    const database = getDb();
    await database.prepare("INSERT INTO scoring_weights (id) VALUES ('default') ON CONFLICT (id) DO NOTHING").run();
    const currentVersion = (await database.prepare<{
        value: string;
    }>("SELECT value FROM catalog_meta WHERE key = 'version'").get())?.value;
    const count = (await database.prepare<{
        cnt: number;
    }>('SELECT COUNT(*) as cnt FROM categories').get())?.cnt ?? 0;
    if (count === 0 || currentVersion !== CATALOG_VERSION) {
        await seedCatalog(database);
        await seedMinimalCatalogForTests(database);
        await database.prepare(`
      INSERT INTO catalog_meta (key, value)
      VALUES ('version', ?)
      ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
    `).run(CATALOG_VERSION);
    }
    await seedRecruitmentRolesAndPostes(database);
    await seedPoleCategories(database);
}
async function seedMinimalCatalogForTests(database: AsyncDb): Promise<void> {
    if (process.env.NODE_ENV !== 'test')
        return;
    const count = (await database.prepare<{ cnt: number }>('SELECT COUNT(*) as cnt FROM categories').get())?.cnt ?? 0;
    if (count > 0)
        return;
    const categories = [
        'core-engineering', 'backend-integration', 'frontend-ui', 'platform-engineering',
        'observability-reliability', 'security-compliance', 'architecture-governance',
        'soft-skills-delivery', 'domain-knowledge', 'ai-engineering', 'qa-test-engineering',
        'infrastructure-systems-network', 'analyse-fonctionnelle', 'project-management-pmo',
        'change-management-training', 'design-ux', 'data-engineering-governance',
        'management-leadership', 'legacy-ibmi-adelia', 'javaee-jboss',
    ];
    for (const [sortOrder, id] of categories.entries()) {
        await database.prepare('INSERT INTO categories (id, label, emoji, sort_order) VALUES (?, ?, ?, ?) ON CONFLICT (id) DO NOTHING')
            .run(id, id, '', sortOrder);
    }
}
async function seedRecruitmentRolesAndPostes(database: AsyncDb): Promise<void> {
    const legacyRoleIds = ['dev-full-stack', 'devops', 'qa-engineer', 'analyste-fonctionnel'];
    await database.prepare(`UPDATE roles SET deleted_at = now()
     WHERE id = ANY($1::text[]) AND deleted_at IS NULL`).run(legacyRoleIds);
    const recruitmentRoles: {
        id: string;
        label: string;
        categories: string[];
    }[] = [
        { id: 'tech-lead-adelia', label: 'Tech Lead Adélia (RPG)', categories: ['domain-knowledge', 'backend-integration', 'soft-skills-delivery', 'core-engineering'] },
        { id: 'dev-senior-adelia', label: 'Dev Senior Adélia (RPG)', categories: ['domain-knowledge', 'backend-integration', 'core-engineering'] },
        { id: 'tech-lead-java', label: 'Tech Lead Java / JBoss', categories: ['core-engineering', 'backend-integration', 'frontend-ui', 'platform-engineering', 'architecture-governance', 'soft-skills-delivery'] },
        { id: 'dev-java-fullstack', label: 'Dev Java Senior Full Stack', categories: ['core-engineering', 'backend-integration', 'frontend-ui', 'platform-engineering', 'architecture-governance'] },
        { id: 'dev-jboss-senior', label: 'Dev JBoss Senior', categories: ['core-engineering', 'backend-integration', 'frontend-ui', 'platform-engineering'] },
        { id: 'architecte-si', label: 'Architecte SI Logiciel', categories: ['architecture-governance', 'core-engineering', 'backend-integration', 'platform-engineering', 'frontend-ui', 'soft-skills-delivery'] },
        { id: 'business-analyst', label: 'Business Analyst', categories: ['analyse-fonctionnelle', 'domain-knowledge', 'project-management-pmo', 'change-management-training', 'soft-skills-delivery', 'design-ux'] },
        {
            id: 'candidature-libre',
            label: 'Candidature Libre',
            categories: [
                'core-engineering', 'backend-integration', 'frontend-ui', 'platform-engineering',
                'observability-reliability', 'security-compliance', 'architecture-governance',
                'soft-skills-delivery', 'domain-knowledge', 'ai-engineering', 'qa-test-engineering',
                'infrastructure-systems-network', 'analyse-fonctionnelle', 'project-management-pmo',
                'change-management-training', 'design-ux', 'data-engineering-governance',
                'management-leadership', 'legacy-ibmi-adelia', 'javaee-jboss',
            ],
        },
    ];
    const syncRoles = database.transaction(async () => {
        for (const role of recruitmentRoles) {
            await database.prepare(`
        INSERT INTO roles (id, label, created_by)
        VALUES (?, ?, 'system')
        ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, deleted_at = NULL
      `).run(role.id, role.label);
            for (const catId of role.categories) {
                const cat = await database.prepare('SELECT 1 FROM categories WHERE id = ?').get(catId);
                if (cat) {
                    await database.prepare(`
            INSERT INTO role_categories (role_id, category_id)
            VALUES (?, ?)
            ON CONFLICT DO NOTHING
          `).run(role.id, catId);
                }
            }
        }
    });
    await syncRoles();
    const posteCount = (await database.prepare<{
        c: number;
    }>('SELECT COUNT(*) as c FROM postes').get())?.c ?? 0;
    if (posteCount === 0) {
        const postes: {
            id: string;
            roleId: string;
            titre: string;
            pole: string;
            headcount: number;
            flexible: boolean;
            expMin: number;
            cigref: string;
        }[] = [
            { id: 'poste-1-tech-lead-adelia', roleId: 'tech-lead-adelia', titre: 'Tech Lead Adélia (RPG)', pole: 'legacy', headcount: 1, flexible: true, expMin: 10, cigref: '3.4' },
            { id: 'poste-2-dev-senior-adelia', roleId: 'dev-senior-adelia', titre: 'Dev Senior Adélia (RPG)', pole: 'legacy', headcount: 1, flexible: true, expMin: 7, cigref: '3.4' },
            { id: 'poste-3-tech-lead-java', roleId: 'tech-lead-java', titre: 'Tech Lead Java / JBoss', pole: 'java_modernisation', headcount: 1, flexible: false, expMin: 10, cigref: '3.4' },
            { id: 'poste-4-dev-java-fullstack', roleId: 'dev-java-fullstack', titre: 'Dev Java Senior Full Stack', pole: 'java_modernisation', headcount: 1, flexible: false, expMin: 7, cigref: '3.4' },
            { id: 'poste-5-dev-jboss-senior', roleId: 'dev-jboss-senior', titre: 'Dev JBoss Senior', pole: 'java_modernisation', headcount: 1, flexible: false, expMin: 7, cigref: '3.4' },
            { id: 'poste-6-architecte-si', roleId: 'architecte-si', titre: 'Architecte SI Logiciel', pole: 'java_modernisation', headcount: 1, flexible: false, expMin: 10, cigref: '4.9' },
            { id: 'poste-7-business-analyst', roleId: 'business-analyst', titre: 'Business Analyst', pole: 'fonctionnel', headcount: 1, flexible: false, expMin: 7, cigref: '2.2' },
            { id: 'candidature-libre', roleId: 'candidature-libre', titre: 'Candidature Libre', pole: 'java_modernisation', headcount: 99, flexible: true, expMin: 0, cigref: '' },
        ];
        const seedPostes = database.transaction(async () => {
            for (const p of postes) {
                await database.prepare(`
          INSERT INTO postes (id, role_id, titre, pole, headcount, headcount_flexible, experience_min, cigref, contrat)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'CDIC')
          ON CONFLICT (id) DO NOTHING
        `).run(p.id, p.roleId, p.titre, p.pole, p.headcount, p.flexible ? 1 : 0, p.expMin, p.cigref);
            }
        });
        await seedPostes();
    }
    const allCatIds = (await database.prepare<{
        id: string;
    }>('SELECT id FROM categories').all()).map((r) => r.id);
    for (const catId of allCatIds) {
        await database.prepare(`
      INSERT INTO role_categories (role_id, category_id)
      VALUES ('candidature-libre', ?)
      ON CONFLICT DO NOTHING
    `).run(catId);
    }
    await database.prepare(`
    INSERT INTO postes (id, role_id, titre, pole, headcount, headcount_flexible, experience_min, cigref, contrat)
    VALUES ('candidature-libre', 'candidature-libre', 'Candidature Libre', 'java_modernisation', 99, 1, 0, '', 'CDIC')
    ON CONFLICT (id) DO NOTHING
  `).run();
    for (const roleId of ['tech-lead-adelia', 'dev-senior-adelia']) {
        await database.prepare(`
      INSERT INTO role_categories (role_id, category_id)
      VALUES (?, 'legacy-ibmi-adelia')
      ON CONFLICT DO NOTHING
    `).run(roleId);
    }
}
async function seedPoleCategories(database: AsyncDb): Promise<void> {
    const poleCatCount = (await database.prepare<{
        c: number;
    }>('SELECT COUNT(*) as c FROM pole_categories').get())?.c ?? 0;
    if (poleCatCount === 0) {
        const poleMapping: Record<string, string[]> = {
            legacy: ['legacy-ibmi-adelia', 'javaee-jboss', 'core-engineering', 'architecture-governance', 'soft-skills-delivery', 'domain-knowledge'],
            java_modernisation: [
                'core-engineering', 'backend-integration', 'frontend-ui',
                'platform-engineering', 'observability-reliability', 'security-compliance',
                'ai-engineering', 'qa-test-engineering', 'infrastructure-systems-network',
                'architecture-governance', 'soft-skills-delivery', 'domain-knowledge',
            ],
            fonctionnel: [
                'analyse-fonctionnelle', 'project-management-pmo', 'change-management-training',
                'design-ux', 'data-engineering-governance', 'management-leadership',
                'architecture-governance', 'soft-skills-delivery', 'domain-knowledge',
            ],
        };
        const seedPoleMap = database.transaction(async () => {
            for (const [pole, cats] of Object.entries(poleMapping)) {
                for (const catId of cats) {
                    const cat = await database.prepare('SELECT 1 FROM categories WHERE id = ?').get(catId);
                    if (cat) {
                        await database.prepare(`
              INSERT INTO pole_categories (pole, category_id)
              VALUES (?, ?)
              ON CONFLICT DO NOTHING
            `).run(pole, catId);
                    }
                }
            }
        });
        await seedPoleMap();
    }
    for (const [pole, category] of [
        ['java_modernisation', 'infrastructure-systems-network'],
        ['legacy', 'javaee-jboss'],
    ] as const) {
        const cat = await database.prepare('SELECT 1 FROM categories WHERE id = ?').get(category);
        if (cat) {
            await database.prepare(`
        INSERT INTO pole_categories (pole, category_id)
        VALUES (?, ?)
        ON CONFLICT DO NOTHING
      `).run(pole, category);
        }
    }
}
export async function getAllEvaluations(): Promise<Record<string, MemberEvaluation>> {
    const rows = await getDb().prepare<{
        slug: string;
        ratings: string;
        experience: string;
        skipped_categories: string;
        declined_categories: string;
        submitted_at: string | null;
        profile_summary: string | null;
    }>('SELECT * FROM evaluations').all();
    const result: Record<string, MemberEvaluation> = {};
    for (const row of rows) {
        result[row.slug] = {
            ratings: safeJsonParse(row.ratings, {}, 'evaluations.ratings'),
            experience: safeJsonParse(row.experience, {}, 'evaluations.experience'),
            skippedCategories: safeJsonParse(row.skipped_categories, [] as string[], 'evaluations.skipped_categories'),
            declinedCategories: safeJsonParse(row.declined_categories, [] as string[], 'evaluations.declined_categories'),
            submittedAt: row.submitted_at,
            profileSummary: row.profile_summary ?? null,
        };
    }
    return result;
}
export async function getEvaluation(slug: string): Promise<MemberEvaluation | null> {
    const row = await getDb().prepare<{
        slug: string;
        ratings: string;
        experience: string;
        skipped_categories: string;
        declined_categories: string;
        submitted_at: string | null;
        profile_summary: string | null;
    }>('SELECT * FROM evaluations WHERE slug = ?').get(slug);
    if (!row)
        return null;
    return {
        ratings: safeJsonParse(row.ratings, {}, 'evaluations.ratings'),
        experience: safeJsonParse(row.experience, {}, 'evaluations.experience'),
        skippedCategories: safeJsonParse(row.skipped_categories, [] as string[], 'evaluations.skipped_categories'),
        declinedCategories: safeJsonParse(row.declined_categories, [] as string[], 'evaluations.declined_categories'),
        submittedAt: row.submitted_at,
        profileSummary: row.profile_summary ?? null,
    };
}
export async function upsertEvaluation(slug: string, ratings: Record<string, number>, experience: Record<string, number>, skippedCategories: string[], declinedCategories: string[] = []): Promise<MemberEvaluation> {
    await getDb().prepare(`
    INSERT INTO evaluations (slug, ratings, experience, skipped_categories, declined_categories)
    VALUES (?, ?, ?, ?, ?)
    ON CONFLICT (slug) DO UPDATE SET
      ratings = EXCLUDED.ratings,
      experience = EXCLUDED.experience,
      skipped_categories = EXCLUDED.skipped_categories,
      declined_categories = EXCLUDED.declined_categories
  `).run(slug, JSON.stringify(ratings), JSON.stringify(experience), JSON.stringify(skippedCategories), JSON.stringify(declinedCategories));
    const row = await getEvaluation(slug);
    if (!row)
        throw new Error(`Evaluation upsert failed for ${slug}`);
    return row;
}
export async function submitEvaluation(slug: string): Promise<MemberEvaluation | null> {
    const now = new Date().toISOString();
    await getDb().prepare('UPDATE evaluations SET submitted_at = ? WHERE slug = ?').run(now, slug);
    return getEvaluation(slug);
}
export async function recordSkillChangesOnSubmit(slug: string): Promise<void> {
    const memberData = await getEvaluation(slug);
    if (!memberData)
        return;
    const rows = await getDb().prepare<{
        skill_id: string;
        new_level: number;
    }>(`SELECT sc.skill_id, sc.new_level
     FROM skill_changes sc
     JOIN (
       SELECT skill_id, MAX(changed_at) AS changed_at
       FROM skill_changes
       WHERE slug = ?
       GROUP BY skill_id
     ) latest ON latest.skill_id = sc.skill_id AND latest.changed_at = sc.changed_at
     WHERE sc.slug = ?`).all(slug, slug);
    const lastKnown = new Map(rows.map((r) => [r.skill_id, r.new_level]));
    const now = new Date().toISOString();
    const insert = getDb().prepare('INSERT INTO skill_changes (slug, skill_id, old_level, new_level, changed_at) VALUES (?, ?, ?, ?, ?)');
    const tx = getDb().transaction(async () => {
        for (const [skillId, level] of Object.entries(memberData.ratings)) {
            const prev = lastKnown.get(skillId);
            if (prev === undefined) {
                if (level > 0)
                    await insert.run(slug, skillId, 0, level, now);
            }
            else if (prev !== level) {
                await insert.run(slug, skillId, prev, level, now);
            }
        }
    });
    await tx();
}
export async function deleteEvaluation(slug: string): Promise<void> {
    await getDb().prepare('DELETE FROM evaluations WHERE slug = ?').run(slug);
}
import type { RoleRow, RoleCategoryRow } from './types.js';
export interface RoleWithCategories {
    id: string;
    label: string;
    createdBy: string;
    createdAt: string;
    categoryIds: string[];
    hasPoste: boolean;
}
export async function getRoles(): Promise<RoleWithCategories[]> {
    const roles = await getDb().prepare<RoleRow>('SELECT * FROM roles WHERE deleted_at IS NULL ORDER BY label').all();
    const allCats = await getDb().prepare<RoleCategoryRow>('SELECT * FROM role_categories').all();
    const posteRoleIds = new Set((await getDb().prepare<{
        role_id: string;
    }>('SELECT DISTINCT role_id FROM postes').all()).map((r) => r.role_id));
    const catsByRole = new Map<string, string[]>();
    for (const rc of allCats) {
        const list = catsByRole.get(rc.role_id) ?? [];
        list.push(rc.category_id);
        catsByRole.set(rc.role_id, list);
    }
    return roles.map((r) => ({
        id: r.id,
        label: r.label,
        createdBy: r.created_by,
        createdAt: r.created_at,
        categoryIds: catsByRole.get(r.id) ?? [],
        hasPoste: posteRoleIds.has(r.id),
    }));
}
export async function getRole(id: string): Promise<RoleWithCategories | null> {
    const role = await getDb().prepare<RoleRow>('SELECT * FROM roles WHERE id = ? AND deleted_at IS NULL').get(id);
    if (!role)
        return null;
    const cats = await getDb().prepare<{
        category_id: string;
    }>('SELECT category_id FROM role_categories WHERE role_id = ?').all(id);
    const posteCount = (await getDb().prepare<{
        c: number;
    }>('SELECT COUNT(*) as c FROM postes WHERE role_id = ?').get(id))?.c ?? 0;
    return {
        id: role.id,
        label: role.label,
        createdBy: role.created_by,
        createdAt: role.created_at,
        hasPoste: posteCount > 0,
        categoryIds: cats.map((c) => c.category_id),
    };
}
export async function createRole(id: string, label: string, categoryIds: string[], createdBy: string): Promise<RoleWithCategories> {
    const tx = getDb().transaction(async () => {
        await getDb().prepare('INSERT INTO roles (id, label, created_by) VALUES (?, ?, ?)').run(id, label, createdBy);
        for (const catId of categoryIds) {
            await getDb().prepare('INSERT INTO role_categories (role_id, category_id) VALUES (?, ?)').run(id, catId);
        }
    });
    await tx();
    const role = await getRole(id);
    if (!role)
        throw new Error(`Role creation failed for ${id}`);
    return role;
}
export async function updateRole(id: string, label: string, categoryIds: string[]): Promise<RoleWithCategories | null> {
    const existing = await getDb().prepare<{
        id: string;
    }>('SELECT id FROM roles WHERE id = ? AND deleted_at IS NULL').get(id);
    if (!existing)
        return null;
    const tx = getDb().transaction(async () => {
        await getDb().prepare('UPDATE roles SET label = ? WHERE id = ?').run(label, id);
        await getDb().prepare('DELETE FROM role_categories WHERE role_id = ?').run(id);
        for (const catId of categoryIds) {
            await getDb().prepare('INSERT INTO role_categories (role_id, category_id) VALUES (?, ?)').run(id, catId);
        }
    });
    await tx();
    return getRole(id);
}
export async function softDeleteRole(id: string): Promise<boolean> {
    const result = await getDb().prepare("UPDATE roles SET deleted_at = now() WHERE id = ? AND deleted_at IS NULL").run(id);
    return result.changes > 0;
}
export async function getRoleCategories(roleId: string): Promise<string[]> {
    const rows = await getDb().prepare<{
        category_id: string;
    }>('SELECT category_id FROM role_categories WHERE role_id = ?').all(roleId);
    return rows.map((r) => r.category_id);
}
export async function getCategoriesForCandidate(candidateId: string): Promise<string[]> {
    const rows = await getDb().prepare<{
        category_id: string;
    }>(`
    SELECT DISTINCT rc.category_id
    FROM candidatures c
    JOIN postes p ON p.id = c.poste_id
    JOIN role_categories rc ON rc.role_id = p.role_id
    WHERE c.candidate_id = ?
  `).all(candidateId);
    if (rows.length > 0)
        return rows.map((r) => r.category_id);
    const legacy = await getDb().prepare<{
        role_id: string | null;
    }>('SELECT role_id FROM candidates WHERE id = ?').get(candidateId);
    return legacy?.role_id ? getRoleCategories(legacy.role_id) : [];
}
export async function getCategoryIdsByPole(): Promise<Record<string, string[]>> {
    const rows = await getDb().prepare<{
        pole: string;
        category_id: string;
    }>('SELECT pole, category_id FROM pole_categories').all();
    const result: Record<string, string[]> = {};
    for (const r of rows) {
        if (!result[r.pole])
            result[r.pole] = [];
        result[r.pole].push(r.category_id);
    }
    return result;
}
