-- Skill Radar canonical PostgreSQL 16 baseline.
-- This file is intentionally idempotent so a migration job or a single boot
-- initializer can assert the baseline before app startup.

CREATE TABLE IF NOT EXISTS evaluations (
  slug TEXT PRIMARY KEY,
  ratings JSONB NOT NULL DEFAULT '{}'::jsonb,
  experience JSONB NOT NULL DEFAULT '{}'::jsonb,
  skipped_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  submitted_at TIMESTAMPTZ,
  profile_summary TEXT,
  declined_categories JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  emoji TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS calibration_prompts (
  category_id TEXT PRIMARY KEY REFERENCES categories(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  tools JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS skills (
  id TEXT PRIMARY KEY,
  category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS skill_descriptors (
  skill_id TEXT NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
  level INTEGER NOT NULL CHECK (level BETWEEN 0 AND 5),
  label TEXT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (skill_id, level)
);

CREATE TABLE IF NOT EXISTS rating_scale (
  value INTEGER PRIMARY KEY CHECK (value BETWEEN 0 AND 5),
  label TEXT NOT NULL,
  short_label TEXT NOT NULL,
  description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comparison_summaries (
  slug_a TEXT NOT NULL,
  slug_b TEXT NOT NULL,
  summary TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (slug_a, slug_b)
);

CREATE TABLE IF NOT EXISTS chat_usage (
  user_id TEXT NOT NULL,
  used_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_usage_user ON chat_usage(user_id, used_at);

CREATE TABLE IF NOT EXISTS skill_changes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  skill_id TEXT NOT NULL,
  old_level INTEGER NOT NULL CHECK (old_level BETWEEN 0 AND 5),
  new_level INTEGER NOT NULL CHECK (new_level BETWEEN 0 AND 5),
  changed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_skill_changes_slug ON skill_changes(slug, skill_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_skill_changes_skill ON skill_changes(skill_id, changed_at);

CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS role_categories (
  role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, category_id)
);

CREATE TABLE IF NOT EXISTS candidates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT '',
  role_id TEXT REFERENCES roles(id),
  email TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  expires_at TIMESTAMPTZ DEFAULT (now() + interval '30 days'),
  ratings JSONB NOT NULL DEFAULT '{}'::jsonb,
  experience JSONB NOT NULL DEFAULT '{}'::jsonb,
  skipped_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  submitted_at TIMESTAMPTZ,
  ai_report TEXT,
  notes TEXT,
  cv_text TEXT,
  ai_suggestions JSONB,
  telephone TEXT,
  pays TEXT,
  linkedin_url TEXT,
  github_url TEXT,
  canal TEXT,
  origine TEXT,
  ai_reasoning JSONB,
  ai_questions JSONB,
  extraction_status TEXT DEFAULT 'idle' CHECK (extraction_status IN ('idle','running','succeeded','partial','failed')),
  extraction_attempts INTEGER DEFAULT 0,
  last_extraction_at TIMESTAMPTZ,
  last_extraction_error TEXT,
  prompt_version INTEGER DEFAULT 1,
  lock_acquired_at TIMESTAMPTZ,
  ai_profile JSONB,
  declined_categories JSONB NOT NULL DEFAULT '[]'::jsonb,
  version INTEGER NOT NULL DEFAULT 1
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_candidates_email_unique
  ON candidates (LOWER(TRIM(email)))
  WHERE email IS NOT NULL AND TRIM(email) <> '';

CREATE TABLE IF NOT EXISTS postes (
  id TEXT PRIMARY KEY,
  role_id TEXT NOT NULL REFERENCES roles(id),
  titre TEXT NOT NULL,
  pole TEXT NOT NULL CHECK (pole IN ('legacy', 'java_modernisation', 'fonctionnel')),
  headcount INTEGER NOT NULL DEFAULT 1,
  headcount_flexible INTEGER NOT NULL DEFAULT 0,
  experience_min INTEGER NOT NULL DEFAULT 0,
  cigref TEXT NOT NULL DEFAULT '',
  contrat TEXT NOT NULL DEFAULT 'CDIC',
  statut TEXT NOT NULL DEFAULT 'ouvert' CHECK (statut IN ('ouvert', 'pourvu', 'ferme')),
  date_publication TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  description TEXT,
  requirements_extraction_status TEXT DEFAULT 'idle' CHECK (requirements_extraction_status IN ('idle','running','succeeded','failed','skipped')),
  requirements_extraction_error TEXT,
  requirements_extracted_at TIMESTAMPTZ,
  requirements_extraction_model TEXT,
  requirements_extraction_run_id TEXT
);

CREATE TABLE IF NOT EXISTS candidatures (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  poste_id TEXT NOT NULL REFERENCES postes(id),
  statut TEXT NOT NULL DEFAULT 'postule'
    CHECK (statut IN ('postule','preselectionne','skill_radar_envoye','skill_radar_complete','entretien_1','aboro','entretien_2','proposition','embauche','refuse')),
  canal TEXT NOT NULL DEFAULT 'site'
    CHECK (canal IN ('cabinet','site','candidature_directe','reseau','cabinet_seyos','cabinet_altaide','local_nc','direct')),
  notes_directeur TEXT,
  taux_compatibilite_poste DOUBLE PRECISION,
  taux_compatibilite_equipe DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  taux_soft_skills DOUBLE PRECISION,
  soft_skill_alerts JSONB,
  taux_global DOUBLE PRECISION,
  role_aware_suggestions JSONB,
  role_aware_reasoning JSONB,
  role_aware_questions JSONB,
  submission_uuid TEXT,
  payload_sha256 VARCHAR(64),
  persisted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (candidate_id, poste_id)
);
CREATE INDEX IF NOT EXISTS idx_candidatures_poste ON candidatures(poste_id, statut);
CREATE INDEX IF NOT EXISTS idx_candidatures_candidate ON candidatures(candidate_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_candidatures_submission_uuid
  ON candidatures(submission_uuid)
  WHERE submission_uuid IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_candidatures_payload_sha256 ON candidatures(payload_sha256);
CREATE INDEX IF NOT EXISTS idx_candidatures_persisted_at ON candidatures(persisted_at);

CREATE TABLE IF NOT EXISTS candidature_events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidature_id TEXT NOT NULL REFERENCES candidatures(id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'status_change'
    CHECK (type IN ('status_change','note','entretien','document','email','email_sent','email_scheduled','email_cancelled','email_failed','email_open','email_clicked','email_delivered','email_complained','email_delay','evaluation_reopened','onboarding','stage_data_changed','email_received','canal_change')),
  statut_from TEXT,
  statut_to TEXT,
  notes TEXT,
  content_md TEXT,
  email_snapshot JSONB,
  stage TEXT,
  updated_at TIMESTAMPTZ,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_candidature_events ON candidature_events(candidature_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_candidature_events_inbound_msgid
  ON candidature_events(candidature_id, (email_snapshot->>'messageId'))
  WHERE type = 'email_received'
    AND email_snapshot IS NOT NULL
    AND email_snapshot->>'messageId' IS NOT NULL;

CREATE TABLE IF NOT EXISTS candidature_documents (
  id TEXT PRIMARY KEY,
  candidature_id TEXT NOT NULL REFERENCES candidatures(id) ON DELETE CASCADE,
  type TEXT NOT NULL DEFAULT 'other'
    CHECK (type IN ('aboro', 'cv', 'lettre', 'entretien', 'proposition', 'administratif', 'other')),
  filename TEXT NOT NULL,
  path TEXT NOT NULL,
  uploaded_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  event_id INTEGER REFERENCES candidature_events(id),
  scan_status TEXT DEFAULT 'pending',
  scan_result TEXT,
  scanned_at TIMESTAMPTZ,
  display_filename TEXT,
  deleted_at TIMESTAMPTZ,
  replaces_document_id TEXT REFERENCES candidature_documents(id)
);
CREATE INDEX IF NOT EXISTS idx_candidature_documents ON candidature_documents(candidature_id);
CREATE INDEX IF NOT EXISTS idx_documents_event ON candidature_documents(event_id);
CREATE INDEX IF NOT EXISTS idx_documents_deleted_at ON candidature_documents(deleted_at);
CREATE INDEX IF NOT EXISTS idx_documents_scan_status ON candidature_documents(scan_status);

CREATE TABLE IF NOT EXISTS aboro_profiles (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  profile_json JSONB NOT NULL,
  source_document_id TEXT,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_aboro_profiles_candidate ON aboro_profiles(candidate_id);

CREATE TABLE IF NOT EXISTS candidature_stage_data (
  candidature_id TEXT NOT NULL REFERENCES candidatures(id) ON DELETE CASCADE,
  stage TEXT NOT NULL,
  data_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT,
  scheduled_at TEXT GENERATED ALWAYS AS (data_json->>'scheduledAt') STORED,
  response_deadline TEXT GENERATED ALWAYS AS (data_json->>'responseDeadline') STORED,
  arrival_date TEXT GENERATED ALWAYS AS (data_json->>'arrivalDateInNc') STORED,
  PRIMARY KEY (candidature_id, stage)
);
CREATE INDEX IF NOT EXISTS idx_stage_data_candidature ON candidature_stage_data(candidature_id);
CREATE INDEX IF NOT EXISTS idx_stage_data_scheduled ON candidature_stage_data(scheduled_at) WHERE scheduled_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_stage_data_deadline ON candidature_stage_data(response_deadline) WHERE response_deadline IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_stage_data_arrival ON candidature_stage_data(arrival_date) WHERE arrival_date IS NOT NULL;

-- remind_at stays TEXT: the app stores Pacific/Noumea wall-clock reminder
-- values and converts them explicitly in daily-recap.ts.
CREATE TABLE IF NOT EXISTS candidature_reminders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidature_id TEXT NOT NULL REFERENCES candidatures(id) ON DELETE CASCADE,
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  remind_at TEXT NOT NULL,
  body_md TEXT NOT NULL DEFAULT '',
  is_done INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  done_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_reminders_candidature ON candidature_reminders(candidature_id);
CREATE INDEX IF NOT EXISTS idx_reminders_due ON candidature_reminders(remind_at) WHERE is_done = 0;

CREATE TABLE IF NOT EXISTS candidate_tags (
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  tag TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (candidate_id, tag)
);
CREATE INDEX IF NOT EXISTS idx_candidate_tags_tag ON candidate_tags(tag);

CREATE TABLE IF NOT EXISTS candidate_extractions (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('cv', 'aboro')),
  run_id TEXT NOT NULL,
  prompt_version INTEGER NOT NULL,
  model_version TEXT NOT NULL,
  input_hash TEXT NOT NULL,
  raw_output JSONB NOT NULL,
  parsed_output JSONB NOT NULL,
  merge_strategy TEXT NOT NULL DEFAULT 'additive'
    CHECK (merge_strategy IN ('additive', 'recruiter-curated', 'replace')),
  cost_eur DOUBLE PRECISION,
  input_tokens INTEGER,
  output_tokens INTEGER,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_candidate_extractions_candidate ON candidate_extractions(candidate_id, type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_candidate_extractions_run ON candidate_extractions(run_id);

CREATE TABLE IF NOT EXISTS candidate_field_overrides (
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  value JSONB NOT NULL,
  source TEXT NOT NULL CHECK (source IN ('recruiter', 'extraction')),
  locked_by TEXT,
  locked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (candidate_id, field_name)
);

CREATE TABLE IF NOT EXISTS extraction_usage (
  user_slug TEXT NOT NULL,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  tokens_spent INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_slug, day)
);

CREATE TABLE IF NOT EXISTS scan_overrides (
  id TEXT PRIMARY KEY,
  document_id TEXT NOT NULL REFERENCES candidature_documents(id) ON DELETE CASCADE,
  verdict TEXT NOT NULL CHECK (verdict IN ('safe', 'quarantine')),
  reason TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_scan_overrides_document ON scan_overrides(document_id, expires_at);

CREATE TABLE IF NOT EXISTS candidate_assets (
  id TEXT PRIMARY KEY,
  candidate_id TEXT REFERENCES candidates(id) ON DELETE CASCADE,
  kind TEXT NOT NULL CHECK (kind IN ('cv_text','lettre_text','raw_pdf','photo')),
  mime TEXT,
  size_bytes INTEGER,
  sha256 TEXT NOT NULL,
  storage_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (candidate_id, kind, sha256)
);
CREATE INDEX IF NOT EXISTS idx_candidate_assets_candidate ON candidate_assets(candidate_id, kind);

CREATE TABLE IF NOT EXISTS cv_extraction_runs (
  id TEXT PRIMARY KEY,
  candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  candidature_id TEXT REFERENCES candidatures(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('skills_baseline','skills_role_aware','profile','critique','reconcile')),
  run_index INTEGER NOT NULL,
  poste_id TEXT REFERENCES postes(id),
  poste_snapshot JSONB,
  catalog_version TEXT,
  prompt_version INTEGER NOT NULL,
  model TEXT NOT NULL,
  cv_asset_id TEXT REFERENCES candidate_assets(id),
  lettre_asset_id TEXT REFERENCES candidate_assets(id),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  status TEXT CHECK (status IN ('running','success','partial','failed')),
  input_tokens INTEGER,
  output_tokens INTEGER,
  payload JSONB,
  error TEXT,
  UNIQUE (candidate_id, run_index)
);
CREATE INDEX IF NOT EXISTS idx_cv_runs_candidate ON cv_extraction_runs(candidate_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_cv_runs_kind ON cv_extraction_runs(candidate_id, kind, started_at DESC);

CREATE TABLE IF NOT EXISTS scoring_weights (
  id TEXT PRIMARY KEY,
  weight_poste DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  weight_equipe DOUBLE PRECISION NOT NULL DEFAULT 0.2,
  weight_soft DOUBLE PRECISION NOT NULL DEFAULT 0.3,
  updated_at TIMESTAMPTZ DEFAULT now(),
  retention_days INTEGER DEFAULT 90
);
INSERT INTO scoring_weights (id) VALUES ('default')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS poste_skill_requirements (
  poste_id TEXT NOT NULL REFERENCES postes(id) ON DELETE CASCADE,
  skill_id TEXT NOT NULL REFERENCES skills(id),
  target_level INTEGER NOT NULL DEFAULT 3 CHECK (target_level BETWEEN 1 AND 5),
  importance TEXT NOT NULL DEFAULT 'requis' CHECK (importance IN ('requis', 'apprecie')),
  source TEXT,
  reasoning TEXT,
  extracted_at TIMESTAMPTZ,
  model TEXT,
  PRIMARY KEY (poste_id, skill_id)
);

CREATE TABLE IF NOT EXISTS catalog_meta (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS pole_categories (
  pole TEXT NOT NULL CHECK (pole IN ('legacy', 'java_modernisation', 'fonctionnel')),
  category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  PRIMARY KEY (pole, category_id)
);

-- Better Auth baseline. Identifiers are quoted where Better Auth expects
-- camelCase or a reserved table name.
CREATE TABLE IF NOT EXISTS "user" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL DEFAULT false,
  image TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  slug TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS session (
  id TEXT PRIMARY KEY,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  token TEXT NOT NULL UNIQUE,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_session_user_id ON session("userId");

CREATE TABLE IF NOT EXISTS account (
  id TEXT PRIMARY KEY,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMPTZ,
  "refreshTokenExpiresAt" TIMESTAMPTZ,
  scope TEXT,
  password TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_account_user_id ON account("userId");

CREATE TABLE IF NOT EXISTS verification (
  id TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ NOT NULL,
  "createdAt" TIMESTAMPTZ DEFAULT now(),
  "updatedAt" TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_verification_identifier ON verification(identifier);

CREATE TABLE IF NOT EXISTS user_shortlists (
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  candidature_id TEXT NOT NULL REFERENCES candidatures(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  note TEXT,
  PRIMARY KEY (user_id, candidature_id)
);
CREATE INDEX IF NOT EXISTS idx_user_shortlists_user ON user_shortlists(user_id, added_at DESC);
