import pg from 'pg'
import crypto from 'crypto'
import Database from './postgres-sync-test-db.js'

function quoteIdentifier(value: string): string {
  return `"${value.replace(/"/g, '""')}"`
}

function scopedUrl(baseUrl: string, schemaName: string): string {
  const url = new URL(baseUrl)
  url.searchParams.set('options', `-csearch_path=${schemaName},public`)
  return url.toString()
}

export async function createTestDb() {
  const globals = globalThis as unknown as {
    __skillRadarBaseDatabaseUrl?: string
    __skillRadarDatabaseUrl?: string
  }
  const baseUrl = globals.__skillRadarBaseDatabaseUrl ?? process.env.DATABASE_URL
  if (!baseUrl)
    throw new Error('[test-db] DATABASE_URL is required')
  globals.__skillRadarBaseDatabaseUrl = baseUrl
  const schemaName = `helper_${crypto.randomUUID().replace(/-/g, '')}`
  const pool = new pg.Pool({ connectionString: baseUrl, max: 1 })
  try {
    const { rows } = await pool.query('SELECT current_database() AS name')
    const databaseName = String(rows[0]?.name ?? '')
    if (!databaseName.includes('test')) {
      throw new Error(`[test-db] Refusing to use non-test database: ${databaseName}`)
    }
    await pool.query(`CREATE SCHEMA ${quoteIdentifier(schemaName)}`)
  } finally {
    await pool.end()
  }
  const url = scopedUrl(baseUrl, schemaName)
  process.env.DATABASE_URL = url
  globals.__skillRadarDatabaseUrl = url

  const db = new Database('postgres-test-helper')
  db.exec(`
    CREATE TABLE IF NOT EXISTS evaluations (
      slug TEXT PRIMARY KEY,
      ratings TEXT NOT NULL DEFAULT '{}',
      experience TEXT NOT NULL DEFAULT '{}',
      skipped_categories TEXT NOT NULL DEFAULT '[]',
      submitted_at TEXT,
      profile_summary TEXT
    );

    CREATE TABLE IF NOT EXISTS categories (
      id TEXT PRIMARY KEY,
      label TEXT NOT NULL,
      emoji TEXT NOT NULL,
      sort_order INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS skills (
      id TEXT PRIMARY KEY,
      category_id TEXT NOT NULL REFERENCES categories(id),
      label TEXT NOT NULL,
      sort_order INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS skill_descriptors (
      skill_id TEXT NOT NULL REFERENCES skills(id),
      level INTEGER NOT NULL CHECK(level BETWEEN 0 AND 5),
      label TEXT NOT NULL,
      description TEXT NOT NULL,
      PRIMARY KEY (skill_id, level)
    );

    CREATE TABLE IF NOT EXISTS rating_scale (
      value INTEGER PRIMARY KEY CHECK(value BETWEEN 0 AND 5),
      label TEXT NOT NULL,
      short_label TEXT NOT NULL,
      description TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS calibration_prompts (
      category_id TEXT PRIMARY KEY REFERENCES categories(id),
      text TEXT NOT NULL,
      tools TEXT NOT NULL DEFAULT '[]'
    );

    CREATE TABLE IF NOT EXISTS comparison_summaries (
      slug_a TEXT NOT NULL,
      slug_b TEXT NOT NULL,
      summary TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (now()),
      PRIMARY KEY (slug_a, slug_b)
    );

    CREATE TABLE IF NOT EXISTS chat_usage (
      user_id TEXT NOT NULL,
      used_at TEXT NOT NULL DEFAULT (now())
    );

    CREATE TABLE IF NOT EXISTS skill_changes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      slug TEXT NOT NULL,
      skill_id TEXT NOT NULL,
      old_level INTEGER NOT NULL CHECK(old_level BETWEEN 0 AND 5),
      new_level INTEGER NOT NULL CHECK(new_level BETWEEN 0 AND 5),
      changed_at TEXT NOT NULL DEFAULT (now())
    );

    CREATE TABLE IF NOT EXISTS catalog_meta (key TEXT PRIMARY KEY, value TEXT);
  `)

  db.prepare('INSERT INTO categories (id, label, emoji, sort_order) VALUES (?, ?, ?, ?)').run('core-engineering', 'Core Engineering', '', 0)
  db.prepare('INSERT INTO skills (id, category_id, label, sort_order) VALUES (?, ?, ?, ?)').run('java', 'core-engineering', 'Java', 0)
  const insertDesc = db.prepare('INSERT INTO skill_descriptors (skill_id, level, label, description) VALUES (?, ?, ?, ?)')
  for (let level = 0; level <= 5; level++) {
    insertDesc.run('java', level, `Level ${level}`, `Java level ${level}`)
  }

  return db
}
